"""Load and retrieve customer segments generated by the segmentation workflow."""

from __future__ import annotations

import pandas as pd

from src.config.paths import PROCESSED_DATA_DIR


SEGMENTS_PATH = PROCESSED_DATA_DIR / "customer_segments.csv"


def load_customer_segments() -> pd.DataFrame:
    """Load the persisted customer clustering output."""
    if not SEGMENTS_PATH.exists():
        raise FileNotFoundError("Customer segments have not been generated.")
    segments = pd.read_csv(SEGMENTS_PATH)
    segments["CustomerID"] = segments["CustomerID"].astype(int)
    return segments


def find_customer_segment(customer_id: int) -> dict | None:
    """Return one customer's saved cluster and persona, if available."""
    segments = load_customer_segments()
    matches = segments.loc[segments["CustomerID"] == customer_id]
    if matches.empty:
        return None
    record = matches.iloc[0]
    return {
        "customer_id": int(record["CustomerID"]),
        "cluster": int(record["Cluster"]),
        "persona": str(record["Persona"]),
    }
